[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["postgres","runtime-tokio-native-tls"] }
tokio = { version = "1.43.0", features = ["full"] }
