[application]

[web.app]

# HTML title tag content
title = "demo_frontend"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[proxy]
backend = "http://localhost:3000"
rewrite = true
